import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import Header from '../components/Header';
import Footer from '../components/Footer';
import MobileMenu from '../components/MobileMenu';

import '../css/output.css';
import '../css/style.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Lash Me E.',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<Header />
				<MobileMenu />
				<main>{children}</main>
				<Footer />
			</body>
		</html>
	);
}
